### ISSUE TITLE
COP-1 Frame Acking Question

### ISSUE THREAD

**Issue by lucas-bremond** [dariol83/ccsds#13]
👋

As I was looking at the COP-1 implementation, I stumbled across the following [code](https://github.com/dariol83/ccsds/blob/5a955c587bedb041eaf088b3bc5b585ac1d27429/eu.dariolucia.ccsds.tmtc/src/main/java/eu/dariolucia/ccsds/tmtc/cop1/fop/FopEngine.java#L521):

```java
int currentNNR = next.getFrame().getVirtualChannelFrameCount();
Set<Integer> expander = new HashSet<>();
for(int i = 0; i < fopSlidingWindow; ++i) {
    expander.add((currentNNR + 1 + i) % 256); // <-- Why the +1 here?
}
// If the set contains the clcw report, all fine
if(expander.contains((int) clcw.getReportValue())) {
    ...
}
```

Do you have a rationale for the `+1`: shouldn't the `expander` set contain the frame count itself, to be acked?

If `fopSlidingWindow = 2`, `getFrame().getVirtualChannelFrameCount() = 5` and `clcw.getReportValue() = 5`,
don't we end up with `expander = {6, 7}`, which does not contain `5` and therefore that frame wouldn't get acked?

I guess I'm probably missing something here, but I thought I'd rather ask ;)

Pretty cool library by the way!

**Comment by dariol83** [comment]
Hi Lucas, 

Thanks a lot for your feedback and for the question.

In short, the acknowledgement that you receive from the CLCW via its report value is not related to 'a single frame', but to 'all frames before the reported one'. In other words, the CLCW report value is telling the FOP engine which is the next frame counter value that the FARM is expecting, meaning that the FARM received all frames before that one.

In order to delete a succesfully transferred frame (i.e. 5 in your example), the report value must contain the value 6. Therefore the expander set is initialised the fopSlidingWindow values, i.e. all the possible report values that will mark the frame as 'acknowledged'. So 6 and 7, in your example.

Remember: the FARM is not expected to acknowledge each and every single frame with a corresponding report value. I might have a FOP sliding window of 20, I can send then TC frames from 0 to 19 (assuming that the CLCW is reporting me a report value = 0 when I start sending) in, let's say, 2 seconds (depending on the transmission bitrate) and, depending on the TM frame generation rate on-board (assume 1 frame per second), I could get back CLCWs with report values like: 3, 7, 13, 18, 20 in the following 5 seconds. With the first report value I see (3), the FOP knows that the FARM processed correctly the first 3 TC frames (0, 1, 2). With the second value (7), the FOP knows that up to TC frame 6 was correctly received, and so on.

I hope it is clearer how it works now, and therefore why there is + 1 there :)

Cheers,
Dario

**Comment by lucas-bremond** [comment]
Ahah!

> the CLCW report value is telling the FOP engine which is the next frame counter value that the FARM is expecting

That was the part I was missing. I was assuming the CLCW to contain the frame counter of the last received frame. I should have read the spec better.

Thank you so much for the clear explanation, and cheers as well!

**Comment by lucas-bremond** [comment]
And while we're at it: I was wondering if the `expander` couldn't be computed only once (and out of loop), like:

```java
while(acked && !this.sentQueue.isEmpty()) {
    ...
    int currentNNR = next.getFrame().getVirtualChannelFrameCount();
    Set<Integer> expander = new HashSet<>();
    for(int i = 0; i < fopSlidingWindow; ++i) {
        expander.add((currentNNR + 1 + i) % 256);
    }
    // If the set contains the clcw report, all fine
    if(expander.contains((int) clcw.getReportValue())) {
        ...
    }
    ...
}
```

could maybe become something along the lines of:

```java
// Out of while loop
int NR = (int) clcw.getReportValue();
Set<Integer> expander = new HashSet<>();
for(int i = 0; i < fopSlidingWindow; ++i) {
    expander.add((NR - 1 - i + 256) % 256);
}

while(acked && !this.sentQueue.isEmpty()) {
    ...

    int currentNNR = next.getFrame().getVirtualChannelFrameCount();
    
    // If the set contains the clcw report, all fine
    if(expander.contains(currentNNR)) {
        ...
    }
    ...
}
```

?

**Comment by dariol83** [comment]
Mmm ... you are using a reversed approach, which might actually work... in fact, if you get for instance a CLCW value equal to e.g. 8, and FopSlWnd=2 it means that frames 7 and 6 are acked. Well, try to change the code and re-run the unit tests. If that works, feel free to propose a pull request for me to integrate, so that you will be given the proper credits :)
