### ISSUE TITLE
Help for example TMProcessor

### ISSUE THREAD

**Issue by femtotron** [dariol83/ccsds#16]
Hi (again),
Despite several hours of efforts, I could not use TMProcessor.java. 
I specified --in_port and --definition as argument but nothing occurs. 

Somebody has already run that file ?  I need some help.

Bests.
Eren

**Comment by dariol83** [comment]
Hi Eren,

I will happily help you, but your questions are not providing any specific context on what you are trying to do and how. In such circumstances, I (and potentially other people) will have issues to answer to your questions. I can only speculate in what you are trying to do, and provide you some information about the TmProcessor class in the examples module. I am also assuming that you know how to launch a Java program after the compilation, how to include the modules that you need and how to declare the class that you want to start. If not, I recommend that you first get used to the Java language and technology, if you wish to approach this library and the Java code on GitHub.

First of all, that is an 'example' and you should not consider it as a final application for end-users (from the README.md:"The main target of the examples module is not to provide final applications ready to be used, rather to explain the different levels and concepts of the libraries, and how to link the various objects together"). Actually, the purpose of the code in this repo is to give you a library that you can use to develop your own programs, not to give you programs. Programs are anyway there as examples and as test tools.

What the TmProcessor does: it opens a TCP/IP connection to an IP/port (--in_host <host> --in_port <port>) and starts to read from the socket. It expects to receive TM transfer frames (no AOS frames, no TC frames), with or without ASM and RS codeblock, with or without FECF, randomized or not (you can contro these aspects with --asm, --rs, --fecf, --derandomize). When the frames are received, space packets are extracted, identified and printed, according to the provided definition file. If parameters are defined in the definition file (not packet parameters, but as declared parameters, see the encdec module and the definition structure), then also the parameters are printed.

Now, the questions and the points that are unclear to me:
1) Do you have a generator of TM frames, which you can use to generate TM frames over TCP/IP in the format requested by the TmProcessor? I would assume so. If the answer is no, then you can use, for testing, the TmGenerator class (always in examples), and specify the --out_port to be the same --in_port used in the TmProcessor.
2) Do you have your own definition file? I assume so. If the answer is no, then you can use, for testing, those located inside eu.dariolucia.ccsds.examples\src\main\resources. If the answer is yes, then assuming that the definitions are correct, you should at least see the transfer frames being printed.
3) When you launch the program, what is the output? Can you provide the command line to me?

On my computer, I could run the TmGenerator with the --definition and --out_port, and the TmProcessor with the same --definition and the --in_port set as the --out_port and I can see reception of frames and decoding of packets, printed by the TmProcessor.

If you want to print the packet parameters, then you have to change a bit the code of the TmProcessor, from line 235. The block below:
```
List<ParameterValue> parameterMap = result.getDecodedParameters();
for(ParameterValue param : parameterMap) {
...
}
```
should become
```
List<DecodingResult.Item> parameterMap = result.getDecodedItems();
for(DecodingResult.Item param : parameterMap) {
     if(param instanceof DecodingResult.Parameter) {
         DecodingResult.Parameter pparam = (DecodingResult.Parameter) param;
         System.out.printf("%s, %d, %d, %s, %d, %d, %s, %s, %s\n",
                                        "Parameter",
                                        firstFrame.getSpacecraftId(),
                                        vc.getVirtualChannelId(),
                                        param.name,
                                        0,
                                        0,
                                        Objects.toString(pparam.value, "<null>"),
                                        pparam.location,
                                        "N/A");
    }
}
``` 
The reason is, that such definition file does not contain any declared parameter.

Example of the output (with the modification above):

> TmTransferFrame, 0, 5, N/A, 1115, 0, N/A, N/A, good
> SpacePacket, 0, 5, DEF6, 36, 304, N/A, N/A, good
> Parameter, 0, 5, ACK_FIELD, 0, 0, 0, DEF6.ACK_FIELD, N/A
> Parameter, 0, 5, PUS_TYPE, 0, 0, 3, DEF6.PUS_TYPE, N/A
> Parameter, 0, 5, PUS_SUBTYPE, 0, 0, 25, DEF6.PUS_SUBTYPE, N/A
> Parameter, 0, 5, FILLER, 0, 0, 0, DEF6.FILLER, N/A
> Parameter, 0, 5, F1, 0, 0, 2, DEF6.F1, N/A
> Parameter, 0, 5, PARAM2, 0, 0, 0.0, DEF6.PARAM2, N/A
> Parameter, 0, 5, PARAM3, 0, 0, 0, DEF6.PARAM3, N/A
> Parameter, 0, 5, PARAM4, 0, 0, false, DEF6.PARAM4, N/A
> Parameter, 0, 5, PARAM5, 0, 0, false, DEF6.PARAM5, N/A
> Parameter, 0, 5, PARAM6, 0, 0, 0000000000000, DEF6.PARAM6, N/A
> Parameter, 0, 5, PARAM7, 0, 0, [B@4bf80c29, DEF6.PARAM7, N/A
> Parameter, 0, 5, PARAM8, 0, 0, 0000000, DEF6.PARAM8, N/A
> Parameter, 0, 5, PARAM9, 0, 0, false, DEF6.PARAM9, N/A
> Parameter, 0, 5, PARAM10, 0, 0, 1970-01-01T00:00:00Z, DEF6.PARAM10, N/A
> Parameter, 0, 5, PARAM11, 0, 0, PT0S, DEF6.PARAM11, N/A
> SpacePacket, 0, 5, DEF3, 15, 302, N/A, N/A, good
> Parameter, 0, 5, ACK_FIELD, 0, 0, 0, DEF3.ACK_FIELD, N/A
> Parameter, 0, 5, PUS_TYPE, 0, 0, 3, DEF3.PUS_TYPE, N/A
> Parameter, 0, 5, PUS_SUBTYPE, 0, 0, 25, DEF3.PUS_SUBTYPE, N/A
> Parameter, 0, 5, PARAM5, 0, 0, false, DEF3.PARAM5, N/A
> Parameter, 0, 5, PARAM7, 0, 0, [B@2d7637e6, DEF3.PARAM7, N/A
> Parameter, 0, 5, PARAM11, 0, 0, PT0S, DEF3.PARAM11, N/A
> SpacePacket, 0, 5, DEF6, 36, 304, N/A, N/A, good
> ...

I hope that the above helps.

Please, for the next questions (if any) make sure to provide first the description of the context, your specific use case and expectation, the execution commands that you use and the output that you get.

Best regards,
Dario

**Comment by femtotron** [comment]
Hi Dario, 
Thank you for your answer. It's work now. I did just not understand how TMProcessor listen tcp port. Your answer helped me very well. 
However I have another question ! is it possible for TMProcessor to read and/or decode specific files (e.g .cadu) ? 

Bests
Eren

**Comment by femtotron** [comment]
Hi Dario, 
Thanks again. Your additionnal example will be very useful. 

I am going to come to you if I need special help.

Thanks again for your responsiveness.

Bests, 
Eren

**Comment by femtotron** [comment]
Hi (again) Dario, 
Is it possible to convert any file (jpg, txt, pdf, etc.) to ccsds format (cadu, vcf, spp) ?

**Comment by dariol83** [comment]
Hi Eran,

I would not use the word "convert", because the CCSDS standards in this repo are not about file formats, rather data link/transport/delivery protocols. So if the question is:"Can I deliver a file using CCSDS protocols and generate the CADUs containing such files?", then the answer is yes, but it depends pretty much on the protocol stack you want to use. For instance:
- You might want to use a protocol stack based on CCSDS TM Data Link or AOS Protocol, conveying CCSDS Space Packets, conveying a proprietary way to segment the files, or
- You might want to use a protocol stack based on CCSDS TM Data Link or AOS Protocol, conveying CCSDS Encapsulation Packets, conveying CCSDS CFDP Protocol Data Units, or the ECSS PUS 13 protocol (the latter not supported by this library natively, but the encdec module has classes and functions to work with PUS-compliant CCSDS Space Packets)
- You might want to use a protocol stack based on CCSDS TM Data Link or AOS Protocol, conveying at virtual channel level your proprietary data units segmenting the file over transfer frames.

There is no easy answer and it depends on your use case. However, this question goes far beyond the purpose of this issue and even beyond the level of support I can provide here, so I will close it now.

Best regards,
Dario

The library can be used to do all the above

**Comment by femtotron** [comment]
Hi Dario, 
Thanks for your return. I was crude in my explanation but actually that is I wanted to talk "protocol" .
However I have a question about one of the functions in TmGenerator. 
So I want to modify TmGenerator.java and generate packets using an input file. Which function accepts data from input file ?  There is generatePacket() but it takes 'definition' as input. 
Is there another function ?

Bests 
Eren

**Comment by dariol83** [comment]
Hi Eren,

I am re-opening this issue just to provide you a brief answer: no, TmGenerator as-is builds space packets based on dummy data, generated according to the provided definition file.
You can modify the TmGenerator to take as input a path to a file, and modify the generatePacket to return a list of space packets instead of a single packet. Each space packet would have set, in its data field (method addData on the SpacePacketBuilder class) a piece of the file. There are of course other things to consider (e.g. generate the last frame if the packet does not complete the frame; have a way to indicate how many segments/packets a file is segmented to, or the length of the file, in order to allow reconstruction). It all depends on your use case, but the library should have everything that you need to write your own software.

Best regards,
Dario

**Comment by femtotron** [comment]
Thank you for answer.

It is helpful!

Bests.
Eren
